occ/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from occ_survey.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^survey/', include('occ_survey.urls', namespace="occ_survey")),
    url(r'^$', index, name="index"),
    url(r'^dashboard/(?P<username>[\w\-]+)/$', dashboard, name="dashboard"),
    url(r'^about/$', about, name="about"),
    url(r'^buttons/$', buttons, name="buttons"),
    url(r'^user_login/$', user_login, name="user_login"),
    url(r'^user_logout/$', user_logout, name="user_logout"),
    url(r'^get_status/$', get_status, name="get_status"),
    url(r'^get_override_status/$', get_override_status, name="get_override_status"),
    url(r'^remote/$', remote, name="remote"),
    url(r'^update_set_points/$', update_set_points, name="update_set_points"),
    url(r'^check_button_override/$', check_button_override, name="check_button_override"),
    url(r'^log_button_override/$', log_button_override, name="log_button_override"), 
    url(r'^unsub/$', unsub_notification, name="unsub"),    
]

occ_survey/urls.py
from django.conf.urls import include, url
from occ_survey import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^survey/(?P<survey_name>[\w\-]+)/$', views.survey, name="survey"),
    url(r'^submit_survey/$', views.submit_survey, name="submit_survey"),
    url(r'^chart_daily_consumption/$', views.chart_daily_consumption, name="chart_cons"),
    url(r'^sendmail/$', views.mail, name="sendmail"),
]

occ_survey/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
import json, datetime
from .mail.exp_mail import *
# Create your views here.

def index(request):
	a = AdminText.objects.get(pk=1)
	adminText = [
		a.update1,
		a.update2,
		a.update3,
	]
	
	context = {"adminText": adminText, }
	try:
		del request.session['redirect_logout']
		context = {"logged_out": 1,}
	except KeyError:
		pass

	return render(request, 'occ_survey/index.html', context)

@login_required
def survey(request, survey_name):
	#get userprofile
	user_profile = UserProfile.objects.get(user=request.user)
	a = AdminText.objects.get(pk=1)
	
	allow = False
	
	if survey_name == "profile":
		if user_profile.profile_isDone == 0:
			allow = True
			survey_cat ={"desc": a.profile}
	elif survey_name =="comfort":
		if user_profile.comfort_isDone == 0:
			allow = True
			survey_cat ={"desc": a.comfort}
	elif survey_name =="control":
		if user_profile.control_isDone == 0:
			allow = True
			survey_cat ={"desc": a.control}
	
	if allow:
		question_list = Question.objects.filter(question_cat=survey_name).order_by("order")
		for question in question_list:
			question.choices = [ 
				question.choice.choice1,
				question.choice.choice2,
				question.choice.choice3,
				question.choice.choice4,
				question.choice.choice5,
			]
			
		survey_cat.update({ 
			"cat": question_list[0].question_cat, 
			"title": question_list[0].question_cat.title(), 
		})
		
		context = { "question_list": question_list, "survey_cat": survey_cat, }
		return render(request, 'occ_survey/survey.html', context)
	else:
		return render(request, 'occ_survey/base.html', {"text": "You have already completed this survey!",})

def submit_survey(request):
	question_count = int(request.POST["question_count"])
	
	for x in range(1, question_count+1):
		question_id = request.POST["Q"+str(x)+"_id"]
		answer = request.POST["Q"+str(x)]
		
		#foreign key
		q = Question.objects.get(id=question_id)
		
		#new Answer object
		a = Answer()
		a.question = q
		a.username = request.user.username
		try:
			a.answer  = int(answer)
		except:
			a.answer = None
			a.answer_text = answer
		
		a.save()
		
	#get UserProfile
	u = UserProfile.objects.get(username=request.user.username)
	if request.POST["survey_cat"] == "profile" :
		u.profile_isDone = 1
	elif request.POST["survey_cat"] == "comfort" :
		u.comfort_isDone = 1
	elif request.POST["survey_cat"] == "control" :
		u.control_isDone = 1
	
	u.save()
	
	#return HttpResponse("Answer to question: " + question_id + " is " + answer)
	return render(request, 'occ_survey/base.html', {"text": "Thank you for submitting!", "homelink": True, })
	
def user_login(request):
	
	if request.user.is_authenticated():
		print request.user
		return render(request, 'occ_survey/index.html', {"logged_out": 2,})
	
	elif request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"]
		
		user = authenticate(username=username, password=password)
		
		if user:
			if user.is_active:
			
				login(request, user)
				if "next" in request.POST:
					return HttpResponseRedirect(request.POST["next"])
				else:
					return HttpResponseRedirect(reverse("index"))
			
			else:
				
				return HttpResponse("Your account was disabled.")
		
		else:
			print "Invalid login details: {0}, {1}".format(username, password)
			return render(request, "occ_survey/login.html", {"login": "failed"})
	
	else:
		if request.method == 'GET' and 'next' in request.GET:
			next = request.GET["next"]
			return render(request, "occ_survey/login.html", {"next": next})
		else:
			return render(request, "occ_survey/login.html", {})

	
@login_required
def user_logout(request):
	logout(request)
	request.session['redirect_logout'] = True
	return redirect('index')

@login_required
def dashboard(request, username):
	if request.user.username != username:
		return render(request, 'occ_survey/base.html', {"text": "You do not have access to this page!",})
	else:
		user = User.objects.get(username=username)
		user_profile = UserProfile.objects.get(user=user)
	
		return render(request, 'occ_survey/dashboard.html', {"user1": user, "user_profile": user_profile, })

@login_required
def chart_daily_consumption(request):
	user_profile = UserProfile.objects.get(user=request.user)
	room2 = user_profile.room
	room = user_profile.room.lower().replace(".", "_")
	
	if "room" in request.GET: #if room exists in GET
		if request.GET["room"]: #if room is not empty
			room = request.GET["room"] #room is already in small and _
			if request.GET["room"] == "rpi_0":
				room2 = "RPi_0"
			else:
				room2 = room.upper().replace("_", ".")

	
	#for debug test other rooms
	#room = "g32_2"
	today = datetime.date.today()
	
	data = {
		"occupancy": [],
		"consumption": [],
		"dates": [],
	}
	
	#number of past days to show: default = 7
	for i in range(0,7) :
		#lighting consumption:
		lighting_list = LogLighting.objects.filter(time__gte= (today-datetime.timedelta(i)))
		lighting_list = lighting_list.filter(time__lt= (today-datetime.timedelta(i-1)))
		lighting_list = lighting_list.filter(**{room: 1})
		consumption = round(len(lighting_list)/60.0, 2)
		data["consumption"].append(consumption)
		
		#occupancy:
		occupancy = []
		try:
			occupancy = LogOccupancy.objects.filter(room = room2).filter(time__gte= (today-datetime.timedelta(i))).filter(time__lt= (today-datetime.timedelta(i-1)))
		
		except:
			pass
		
		time = 0
		
		if occupancy:
			for j in range(0, len(occupancy)-1):
				if occupancy[j].state == 1 and occupancy[j+1].state == 0:
					time += (occupancy[j+1].time - occupancy[j].time).seconds	
					
			time = round( time/3600.0, 2)
		
		data["occupancy"].append(time)
		
		#dates:
		if i == 0 :
			data["dates"].append("Today")
		else:
			data["dates"].append((today - datetime.timedelta(i)).strftime("%d-%b"))
	
	return HttpResponse(json.dumps(data))

#view to explain the experiment
def about(request):
	return render(request, 'occ_survey/about.html', {})

#view to explain how the buttons function	
def buttons(request):
	return render(request, 'occ_survey/buttons.html', {})

def mail(request):
	user_list = UserProfile.objects.filter(comfort_isDone=0)
	text = []
#	spotMail(user_list[0].user)
	for each in user_list:
		phase2Mail(each.user)
		text.append(each.user.email)
	return HttpResponse(json.dumps(text))

#view to extract live status from db, needs to pass room name with GET
def get_status(request):
	if request.GET:
		room = request.GET["room"].lower().replace(".", "_")
		room2 = request.GET["room"]
	else:
		user_profile = UserProfile.objects.get(user=request.user)
		room = user_profile.room.lower().replace(".", "_")
		room2 = user_profile.room
	
	time = datetime.datetime.now()
	lights = LogLighting.objects.values_list(room, flat=True).order_by('-id')[:1][0]
	lux = LogLux.objects.values_list(room, flat=True).order_by('-id')[:1][0]
	
	setpoints = ControlSetPoints.objects.get(room=room2) 
	td = setpoints.td
	lux_th = setpoints.lux_th
	upp_th = setpoints.upp_th
	
	data = {
		"ok": True,
		"res": {
			"room": room2,
			"time": time.strftime("%c"),
			"lights": lights,
			"lux": lux,
		},
		"res2": {
			"td": td,
			"lux_th": lux_th,
			"upp_th": upp_th,
		},
	}
	return HttpResponse(json.dumps(data, sort_keys=True))

# if request = GET, updates remote switch count, if = POST, updates control set points
def remote(request):
	if request.method == "GET":
		if "switch" in request.GET:
			user_profile = UserProfile.objects.get(user=request.user)
			user_profile.remote_switch_count += 1
			user_profile.save()
			return HttpResponse("switched from remote")
		
		return HttpResponse("no changes")
		
	elif request.method == "POST":
		#post the changes into control_changes and run sort control_adjustments
		err_msg = ""
		room = request.POST["room"]
		room2 = request.POST["room"].lower().replace(".", "_")
		td_new = int(request.POST["td_setting_new"])
		lux_th_new = int(request.POST["lux_th_new"])
		upp_th_new = int(request.POST["upp_th_new"])
		setpoints = ControlSetPoints.objects.get(room=room)
		luxWLights = ControlLuxWLights.objects.values_list(room2, flat=True).order_by('-id')[:1][0]
		
		#boundaries
		if upp_th_new > 1500:
			upp_th_new = 1500
		
		if lux_th_new > 500:
			lux_th_new = 500
		
		if lux_th_new < 0:
			lux_th_new = 0
		
		if td_new < 0:
			td_new = 1
		elif td_new > 15:
			td_new = 15
		
		#make sure new values respect the original difference which is luxWLights
		del_lux_th = lux_th_new - setpoints.lux_th
		del_upp_th = upp_th_new - setpoints.upp_th
		del_th = upp_th_new - lux_th_new
		
		#first check if del_th < luxWLights
		if (del_th < luxWLights):		
			#del_upp_th has to be larger or equal than del_lux_th
			if (del_upp_th < del_lux_th):
				#if delta upp th is smaller, then set delta upp th to delta lux th and change upp_th_new
				del_upp_th = del_lux_th
				upp_th_new = del_upp_th + setpoints.upp_th
				err_msg = "The difference between the your new min. illuminance threshold and max. illuminance threshold is too small. It has been automatically changed for you."
		
		
		#insert new changes object
		changes = ControlChanges(room=room)
		# new set points
		changes.lux_th_new = lux_th_new
		changes.upp_th_new = upp_th_new
		changes.td_new = td_new
		# current set points at time of change
		changes.lux_th = setpoints.lux_th
		changes.upp_th = setpoints.upp_th
		changes.td = setpoints.td
		changes.save()
		
		#update current setpoints
 		setpoints.td = td_new
 		setpoints.lux_th = lux_th_new
 		setpoints.upp_th = upp_th_new
 		setpoints.override = 1
 		setpoints.save()
 		
		#update adjustments
		adj = ControlAdjustments.objects.get(room=room)
		change_list = ControlChanges.objects.filter(room=room).filter(date__gte= today-datetime.timedelta(14))

occ_survey/templates/occ_survey/about.html
{% extends "occ_survey/base.html" %}

{% load staticfiles %}


{% block body_block %}
	
	<div class="container">	
        
		<div class="index-section">
			<h2>About</h2>
			<p>The Adaptive Systems Laboratory will be conducting a lighting control experiment in selected offices on the G floor of HPZ building. A lighting control system that adapts automatically to the occupants' preferences and behaviours will be installed in each office. The experiment will take place from the middle of June 2015 to the end of September 2015.</p>
        </div>
        <div id="about-control"></div>
        <div class="index-section">
			<h3>The Lighting Control System</h3>
			<p>An independent system will be installed in each office. It consists of a light sensor, an occupancy sensor and a mini-computer. The control functions simply via two set-points: minimum inoccupancy time delay and illuminance threshold.
			<p><u>Minimum Inoccupancy Time Delay</u></p>
			<p>A typical occupancy sensor works by employing a fixed minimum time delay (TD) value. In conventional offices, this is normally set to about 15 minutes. This means that the room will only be deemed unoccupied (and have its lights switched off) if the sensor does not detect any motion during the previous 15 minutes.</p>
			<p>We believe that this arbitrarily set TD value is often too large and leads to energy wastage. We have therefore implemented an algorithm based on a simple statistical model to calculate a unique TD value for each office based on the occupancy data collected. The calculation is based only on data gathered during the past month so as to continually adapt to any changes in the office.</p>
			<p><u>Illuminance Threshold</u></p>
			<p>Likewise, we believe that the illuminance threshold is occupant- or office-specific. For this, we record the illuminance value each time the lights are switched on in the office. The mean or median value is then taken, whichever is lower, as the minimum illuminance threshold. The maximum illuminance threshold is  calculated by adding the illuminance provided by the artificial lights in the office. These two values are then used to determine if there is sufficient illuminance in the office.</p>
			<br />
			<p>These two set points are calculated at the end of every day. The control will determine if the room requires lighting via these two set-points. In short, the lights will be switched on when the room is occupied and there is insufficient illuminance; they will be switched off when the room is unoccupied or when there is too much illuminance.</p>
			<p>
			<br/>
			<h4>Control Override</h4>
			<p>User will have the option to manually override the control set points in certain phases of the experiment. Whenever a manual override is executed, the control will act according to these manually set parameters until the next calculation (at the end of every day) or when the manual override is disabled. The differences between the manually set parameters and the automatically generated ones are recorded and used as inputs for subsequent calculations.
			</p>
        </div>
        
        <div class="index-section">
			<h3>Objectives</h3>
			<p>We have concluded from our previous experiment that the implementation of such a lighting control system can lead to significant energy savings. The main objective of this experiment is then to investigate the effects of such the system on occupants' comfort.</p>
			<p>The optimal goal will be that the control system can save energy at zero or negative expense of occupants' comfort.</p>
        </div>
        
        <div class="index-section">
			<h3>Experimental Outline</h3>
			<br />
			<img src="{% static 'occ_survey/images/experiment_outline.png' %}" class="img-responsive center-block" alt="experiment outline"></img>
			<p>The experiment will be split into 2, possibly 3 phases (refer to chart above).</p> 
			<p>There will be no lighting control system in place during the first phase. Occupants will operate the lights manually with the push button switches in their offices. This phase will serve as a reference in terms of both electricity consumption and comfort for comparison with the later phases.</p>
			<p>The lighting control system will be put in operation in the second phase. The lighting will be controlled automatically, but occupants will also retain manual control with the push button switches. In addition, a dashboard on a web interface will be provided to each occupant, with which he/she will be able to:</p>
			<ol>
				<li>view the lighting energy consumption in his/her office</li>
				<li>override the control system</li>
				<li>change the set points of the control system.</li>
			</ol>
			<p>A third possible phase may be conducted depending on circumstances. This phase will include an immediate feedback loop in the control algorithm such that overrides will be processed and learned by the system instantly, removing the need for the occupant to change the set points manually.</p>
			<br />
			<p>In order to conduct the comfort study, a series of questionnaires will be sent out via email. All participants will be required to fill out a profile questionnaire at the beginning. This is used to determine individual preferences with regards to lighting and visual comfort.</p>
			<p>A comfort questionnaire will be sent out at the end of the first phase to assess each occupant's comfort for the duration of the phase.</p>
			<p>The same comfort questionnaire will be sent out at the end of the second phase in order for us to evaluate the effects of the control system on the occupants. A questionnaire specific to the control system will also be sent out at this point.</p>
			<p>Should a third phase be conducted, a set of questionnaires similar to that sent out at the end of phase 2 will be sent out.</p>  
			
        </div>
        
        <div class="index-section">
			<h3>Your Task</h3>
			<br />
			<p>Your task is to simply assist us by filling out each of the questionnaires we send you as accurately as you can. We will also appreciate any feedback with regards to the dashboard interface, control system or whatever that pleases or displeases you.  
        </div>
        
        <div class="index-section">
			<h3>Links</h3>
			<p>If you are interested in finding out more about the control system and our previous experiment, please refer to the following link.</p>
			<p>&nbsp&nbsp&nbsp&nbsp<a href="http://www.sciencedirect.com/science/article/pii/S0378778815001759" style="
    font-size: 12px;" target="_blank">Z Nagy, FY Yong, M Frei, A Schlueter - Occupant centered lighting control for comfort and energy efficient building operation.</a></p>
    		<p>For any other queries, please direct them <a href="mailto:adaptive.systems.lab.ethz@gmail.com">here</a>.</p>
        </div>

    </div>
    
{% endblock %}

occ_survey/templates/occ_survey/dashboard.html
{% extends "occ_survey/base.html" %}

{% load staticfiles %}

{% block head_block %}
<link href="{% static 'occ_survey/bootstrap/css/bootstrap-switch.min.css' %}" rel="stylesheet">
{% endblock %}

{% block body_block %}

<div class="container">
	
	<div class="row">
		<div class="col-sm-12">
		<div class="index-section">
			<h3>Uncompleted Tasks:</h3>
			<ul>
				{% if user_profile.profile_isDone == 0 %}
				<li><a href="{% url 'occ_survey:survey' 'profile' %}">Complete Profile Questionnaire</a></li>
				{% endif %}
				{% if user_profile.comfort_isDone == 0 %}
				<li><a href="{% url 'occ_survey:survey' 'comfort' %}">Complete Comfort Questionnaire</a></li>	
				{% endif %}
			</ul>
			{% if user_profile.profile_isDone == 1 and user_profile.comfort_isDone == 1 %}
			<p>No current tasks.</p>
			{% endif %}
		</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
		<div class="index-section-head">
			<h3>My Controls: <span class="h2">{{ user_profile.room }}</h2></span></h3>
		</div>
		</div>

		<div class="col-sm-6">
		<div class="index-section" style="height: 300px">
			<div class="status-box">
				<h4>Status <span id="time_updated" class="h6"></span></h4>
				<p></p>
				<p>Lights: <input id="lightSwitch" type="checkbox" data-off-text="OFF" data-on-text="ON" class="lightSwitch" data-size="mini"></p>
				<p>Illuminance: <span id="lux_reading"></span> lux</p>
				<p><button id="refresh_status" class="btn btn-xs btn-default">Refresh</button>
				
			</div>
		</div>
		</div>
		<div class="col-sm-6">
		<div class="index-section" style="height: 300px;">
			<div class="status-box">
				{# block for settings #}
				{% if user_profile.room == "G26.1" or user_profile.room == "G26.2" or user_profile.room == "G31.1" or user_profile.room == "G31.2" %}
				<h4>Settings</h4>
				<p>Due to the malfunction of the motion sensors in your office, the control system is at the moment inactive.</p>
				<p>We are working to resolve the issue.</p>

				{% else %}
				<h4>Settings</h4>
				<form id="change-settings-form" class="form-inline" method="post" action="">
				{% csrf_token %}
					
					<p data-toggle="tooltip" data-placement="left" data-delay= '{ "show": 100, "hide": 300 }' title="The control will switch off the lights after this amount of inactivity.<br>Value between 1 and 15.">Min. Inoccupancy Time Delay: <span id="td_setting"></span> mins 
					<input style="height: 25px; width: 57px; float:right" type="text" class="form-control change-settings hidden" id="td_setting_new" name="td_setting_new" placeholder="Min. Time Delay" value="" ></p>
					
					<p data-toggle="tooltip" data-placement="left" data-delay= '{ "show": 100, "hide": 300 }' title="The control will switch on the lights when the illuminance falls below this value.<br>Value between 0 and 500.<br>Set this value to 0 if you want to stop the control from turning the lights on.">Min. Illuminance Threshold: <span id="lux_th"></span> lux 
					<input style="height: 25px; width: 57px; float:right" type="text" class="form-control change-settings hidden" id="lux_th_new" name="lux_th_new" placeholder="Min. Illuminance Threshold" value="" ></p>
					
					<p data-toggle="tooltip" data-placement="left" data-delay= '{ "show": 100, "hide": 300 }' title="The control will switch off the lights when the illuminance goes above this value.<br>Max value of 1500.">Max. Illuminance Threshold: <span id="upp_th"></span> lux 
					<input style="height: 25px; width: 57px; float:right" type="text" class="form-control change-settings hidden" id="upp_th_new" name="upp_th_new" placeholder="Max. Illuminance Threshold" value="" ></p>
					<input type="text" class="hidden" name="room" value="{{ user_profile.room }}">
				</form>	

				<button type="button" id="refresh_settings" class="btn btn-default btn-xs">Refresh</button>
				<button type="button" id="change_settings" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="bottom" data-delay= '{ "show": 100, "hide": 1000 }' title="This will allow you to override the control set points.<br>Do not change anything if you do not know what you are doing.<br>Refer to <a href='{% url 'about' %}#about-control' target='_blank'>About</a> for more details on how the control works.">Change Settings</button>
				&nbsp;<button type="button" id="submit_settings" class="btn btn-primary btn-xs change-settings hidden">Submit</button>
				<br/><br/>
				<div id = "override_status" class="hidden">
					<p style="color: #DB6480;">User Override is currently Active!</p>
					<form id="override-form">
						{% csrf_token %}
						<button type="button" id="override" class="btn btn-danger btn-sm">Click here to disable override and return to default settings.</button>
						<input type="text" class="hidden" name="room" value="{{ user_profile.room }}">
					</form>
				</div>
				{% endif %}
				
			</div>
		</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-12">
		<div class="index-section">
			<div class="form-inline">
			<h3>Statistics: 
			{% if user.username == "admin" or  user.username == "zoltan" %}
			<span>
				<select id="selected_room" class="form-control">
					<option value="" selected>--Select a Room--</option>
					<option value="g22">G22</option>
					<option value="g23">G23</option>
					<option value="g24">G24</option>
					<option value="g25_1">G25.1</option>
					<option value="g25_2">G25.2</option>
					<option value="g26_1">G26.1</option>
					<option value="g26_2">G26.2</option>
					<option value="g31_1">G31.1</option>
					<option value="g31_2">G31.2</option>
					<option value="g32_1">G32.1</option>
					<option value="g32_2">G32.2</option>
					<option value="rpi_0">RPi_0</option>
				</select>
			</span>
			{% endif %}
			<span><button type="button" id="db_toggle_charts" class="btn btn-default btn-sm">Show</button></span>
			</h3>
			</div>
			
			
			
			<div id="charts" class="hidden">
			<h4>Room <span id="chart_room"></span> | Lighting Energy Consumption and Occupancy* for the past week:</h4>
			<p style="font-size:12px">*values for occupancy are approximated and may not reflect the actual time of occupancy in the office</p>
			<br>
			<div id="myChart2" style="height: 400px; width: 100%"></div>
			
			</div>
			
			
		</div>
		</div>
	</div>
	<!-- end block for controls and chart -->
	

</div>

{% endblock %}

{% block script_block %}
<script type="text/javascript"
          src="https://www.google.com/jsapi?autoload={
            'modules':[{
              'name':'visualization',
              'version':'1.1',
              'packages':['corechart']
            }]
          }"></script>
          
<script>
	// url called in ajax_get_script in dashboard.js
	var default_room = "{{ user_profile.room }}"; 
	var url_charts = "{% static 'occ_survey/js/charts.js' %}";
	var url_get_status = "{% url 'get_status' %}";
	var url_get_override_status = "{% url 'get_override_status' %}";
	var url_get_chart_data = "{% url 'occ_survey:chart_cons' %}";
	var url_remote = "{% url 'remote' %}";
	var username = "{{ user.username }}";
</script>
<script src="{% static 'occ_survey/bootstrap/js/bootstrap-switch.min.js' %}"></script>
<!-- js for dashboard.html page -->
<script src="{% static 'occ_survey/js/dashboard.js' %}"></script>
{% endblock %}

occ_survey/templates/occ_survey/survey.html
{% extends "occ_survey/base.html" %}

{% load staticfiles %}


{% block body_block %}

	<div class="container">
	<div class="header">
	<h2>Hello {{ user.first_name }}</h2>
	<h1>{{ survey_cat.title }} Questionnaire</h1>
	<p>{{ survey_cat.desc }}</p>
	</div>
	
	<br />
	<form id="profile-survey" class="form-group" action="{% url 'occ_survey:submit_survey' %}" method="post">
	{% csrf_token %}	
		{% if question_list %}
		{% for question in question_list %}
		<div class="choice-box">
			<!-- <h4 style="margin-left:10px">Question {{ forloop.counter }}:</h4> -->
		
			<div class="panel panel-default panel-choices">
				<div class="panel-heading">
					<h3 class="panel-title">{{ question.question_text }}</h3>
				</div>
			</div>
		
			<div class="table">
				<table class="table table-condensed table-choices">
					<!--	separate into the types of questions	 -->
					{% if question.choice.type == "radio" %}
					<tr>
						{% for each in question.choices %}
							{% if each %}
							<td>{{ each }}</td>
							{% endif %}
						{% endfor %}
					</tr>

					<tr>
						{% for each in question.choices %}
						{% if each %}
						<td><input type="radio" name="Q{{ forloop.parentloop.counter }}" value="{{forloop.counter}}"></td>
						{% endif %}
						{% endfor %}
						<input type="hidden" name="Q{{ forloop.counter }}_id" value={{ question.id }}>
					</tr>
					{% elif question.choice.type == "open" %}
					<tr>
						<td><textarea class="form-control" name="Q{{ forloop.counter }}" placeholder="your input here.." rows="3"></textarea></td>
						<input type="hidden" name="Q{{ forloop.counter }}_id" value={{ question.id }}>
					</tr>
					{% endif %}
				</table>
			</div>
		</div>
			{% if forloop.last %}
			<input type="hidden" name="question_count" value="{{forloop.counter}}">
			{% endif %}
		{% endfor %}
		
		<input type="hidden" name="survey_cat" value="{{survey_cat.cat}}">
		{% endif %}
	
		<div class="choice-box">	
		<p>Please make sure you have filled out all the questions before clicking on submit.</p>
		<p><input id="profile-submit" class="btn btn-default" type="submit" value="Submit" disabled="disabled"></p>
		</div>
	</form>
	
		<p id="debug"></p>
{% endblock %}
{% block script_block %}
	<script src="{% static 'occ_survey/js/profile.js' %}"></script>
{% endblock %}